# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ckb < Formula
  desc "Code intelligence orchestration layer for AI-assisted development"
  homepage "https://github.com/SimplyLiz/CodeMCP"
  version "8.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.3.0/ckb_8.3.0_darwin_amd64.tar.gz"
      sha256 "420f8795716767110e584bd6b8382897059d5d9b5e13cbb64a5ca79277908d8c"

      define_method(:install) do
        bin.install "ckb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.3.0/ckb_8.3.0_darwin_arm64.tar.gz"
      sha256 "6e7f215e195955ddbe98383cef640c9899cca7fb1c518e61eb2a4ea949f20809"

      define_method(:install) do
        bin.install "ckb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.3.0/ckb_8.3.0_linux_amd64.tar.gz"
      sha256 "74f046eb4a73d6387a3fcc98eebe6fc2cdad5a00f2e80f7494d96d52dbce5aff"
      define_method(:install) do
        bin.install "ckb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.3.0/ckb_8.3.0_linux_arm64.tar.gz"
      sha256 "ccc60b6793ac70b7ed5393766939a47b9703a00c87e273be74211d05503f0488"
      define_method(:install) do
        bin.install "ckb"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ckb version")
  end
end
