# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ckb < Formula
  desc "Code intelligence orchestration layer for AI-assisted development"
  homepage "https://github.com/SimplyLiz/CodeMCP"
  version "8.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.1.0/ckb_8.1.0_darwin_amd64.tar.gz"
      sha256 "7d380814a55c1dad96180944de059bc8396678455b24717d7f5b49bd44ba8599"

      def install
        bin.install "ckb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.1.0/ckb_8.1.0_darwin_arm64.tar.gz"
      sha256 "411ae9b120d7231711a5689387e1563a78bbadb21ceb689710fa52de53adad90"

      def install
        bin.install "ckb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.1.0/ckb_8.1.0_linux_amd64.tar.gz"
      sha256 "451ffab6e312fe83acd19fc37f9de33f7055cbe4248cb5148e0de985805abdcd"
      def install
        bin.install "ckb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.1.0/ckb_8.1.0_linux_arm64.tar.gz"
      sha256 "06382fbd97c837b47b98c7e2303536fb3b9a8adb82cd337717af000df24d15bc"
      def install
        bin.install "ckb"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ckb version")
  end
end
