# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ckb < Formula
  desc "Code intelligence orchestration layer for AI-assisted development"
  homepage "https://github.com/SimplyLiz/CodeMCP"
  version "8.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.0.5/ckb_8.0.5_darwin_amd64.tar.gz"
      sha256 "34fe177cf35434f9b7283868bf3ce4922f627294d883818a3b04d7f73579e349"

      def install
        bin.install "ckb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.0.5/ckb_8.0.5_darwin_arm64.tar.gz"
      sha256 "5b9e9e33d8a51c32e4f7c44656e0adae1580402c26ec77525caa84ccdad8feb2"

      def install
        bin.install "ckb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.0.5/ckb_8.0.5_linux_amd64.tar.gz"
      sha256 "cb82fb3f9f57d6f11f7a514a970753f3204f0125419f81a2f471d5e51e55cff2"
      def install
        bin.install "ckb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SimplyLiz/CodeMCP/releases/download/v8.0.5/ckb_8.0.5_linux_arm64.tar.gz"
      sha256 "be2ac3fee58a3f5c5082dfe278942ff5e89935bb5a78c720af8ef5dd8c580556"
      def install
        bin.install "ckb"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ckb version")
  end
end
